apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mlapi.name" . }}
  namespace: {{ .Values.app.env  }}
  labels:
  {{- include "mlapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ template "mlapi.name" . }}
  template:
    metadata:
      labels:
        {{- include "mlapi.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ template "mlapi.name" . }}
          image: shamik13/{{ template "mlapi.name" . }}:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          resources:
           {{- toYaml .Values.app.computerc | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ template "mlapi.name" . }}