apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.name }}-dep
  namespace: {{ .Values.app.env  }}
  labels:
  {{- include "obj.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.name }}
  template:
    metadata:
      labels:
        {{- include "obj.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.name }}
          image: {{ .Chart.name }}:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          resources:
           {{- toYaml .Values.app.computerc | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ .Chart.name }}-config