{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "mlapi.name" . }}
  namespace: {{ .Values.app.env  }}
  annotations:
    {{- include "mlapi.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.hpa.maxreplicas }}
  minReplicas: {{ .Values.hpa.minrplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: {{ template "mlapi.name" . }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.cuputi }}
{{- end -}}