apiVersion: v1
kind: Service
metadata:
  name: {{ template "mlapi.name" . }}
  namespace: {{ .Values.app.env  }}
  labels:
  {{- include "mlapi.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 5000  # fixed because the application is exposed in 5000 port
    targetPort: 5000
    nodePort: {{ .Values.app.svc.nodeport }}
  selector:
    app: {{ template "mlapi.name" . }}
  type: NodePort