apiVersion: v1
kind: Service
metadata:
  name: mlapi-service
  namespace: {{ .Values.app.env  }}
  labels:
  {{- include "mlapi.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: {{ .Values.app.svc.nodeport }}
  selector:
    app: mlapi
  type: NodePort