apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-service
  namespace: {{ .Values.app.env  }}
  labels:
  {{- include "obj.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: {{ .Values.app.svc.nodeport }}
  selector:
    app: {{ template "fullname" . }}
  type: NodePort