app:
  replicas: 1
  env: stg
  container:
    image: shamik13/mlapi:d548848950c9ecdad72aaa83f418dd54f714d02b
  computerc:
    limits:
      cpu: 0.4
      memory: 600Mi
    requests:
      cpu: 0.4
      memory: 600Mi
  svc:
    nodeport: 32501

hpa:
  enabled: false


config:
  name: config.yaml
  data: 
    timeout: 10s
    logfile: /app/var/log.txt
    database:
      ip: 10.20.30.20
      name: mlapi-db