app:
  replicas: 6
  env: prod
  container:
    image: shamik13/mlapi:d548848950c9ecdad72aaa83f418dd54f714d02b
  computerc:
    limits:
      cpu: 0.4
      memory: 1Gi
    requests:
      cpu: 0.4
      memory: 1Gi
  svc:
    nodeport: 32500

hpa:
  enabled: true
  maxreplicas: 10
  minrplicas: 4
  cuputi: 90

config:
  name: config.yaml
  data: 
    timeout: 2s
    logfile: /app/var/log.txt
    database:
      ip: 120.21.31.10
      name: ui-prod