name: Deploy to Minikube k8s

on:
  workflow_dispatch:
    inputs:
      chartName:
        description: Name of the chart to deploy
        required: true
      chartVersion:
        description: If you want to install a specific chart version
        required: false
      env:
        description: Which environment to deploy in
        required: true


jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Add Helm Repository
        run: |
          helm repo add mycharts "${{ secrets.CHART_REPO_URL }}"
          helm repo update

      - name: Install or Upgrade Helm Chart and Test
        run: |
          cd infra/${{ github.event.inputs.chartName }}
          if [[ ! -z "${{ github.event.inputs.chartVersion }}" ]]; then
            helm upgrade --install ${{ github.event.inputs.chartName }}-${{ github.event.inputs.env }} mycharts/${{ github.event.inputs.chartName }} \
            -f values-${{ github.event.inputs.env }}.yaml --namespace ${{ github.event.inputs.env }} --version ${{ github.event.inputs.chartVersion}} \
            --wait
          else
            helm upgrade --install ${{ github.event.inputs.chartName }}-${{ github.event.inputs.env }} mycharts/${{ github.event.inputs.chartName }} \
            -f values-${{ github.event.inputs.env }}.yaml --namespace ${{ github.event.inputs.env }}  \
            --wait
          fi
          helm test --namespace ${{ github.event.inputs.env }} ${{ github.event.inputs.chartName }}-${{ github.event.inputs.env }}
          helm list -A