name: Deploy to Minikube k8s

on:
  workflow_dispatch:
    inputs:
      chartName:
        description: Name of the chart to deploy
        required: true
      env:
        description: Which environment to deploy in
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Add Helm Repository
        run: |
          helm repo add mycharts "${{ secrets.CHART_REPO_URL }}"
          helm repo update
          shell: bash

      - name: Install or Upgrade Helm Chart
        run: |
          cd infra/${{ github.event.inputs.chartName }}
          helm upgrade --install ${{ github.event.inputs.chartName }}-${{ github.event.inputs.env }} mycharts/${{ github.event.inputs.chartName }} \
          -f values-${{ github.event.inputs.env }}.yaml --namespace ${{ github.event.inputs.env }} \
          --wait
          helm list -A
          shell: bash